name: ios_audio
description: Demo app for iOS background audio pauses.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  audio_service: ^0.14.1
  intl: ^0.16.1
  just_audio: ^0.4.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cowbell.mp3
